services:
  cra:
    image: cra:0.0.1
    ports:
      - "3030:80"
    volumes:
      #- "./nginx.conf:/etc/nginx/nginx.conf"
      - "./.env.docker:/usr/share/nginx/.env"
    environment:
      - "TZ=Asia/Seoul"
